### ISSUE TITLE
mpc.to_bits doesn't seem to work.

### ISSUE THREAD

**Issue by danxinnoble** [lschoe/mpyc#17]
I wrote the following program, modmath.py:
```
import numpy as np
from mpyc.runtime import mpc
async def main():
    await mpc.start()
    secint19 = mpc.SecFld(2**255 - 19)
    a = secint19(10)
    a_bits = mpc.to_bits(a, 6)
    a_bits = await mpc.output(a_bits)
    print("a_bits=", str(a_bits))
    await mpc.shutdown()

if __name__ == '__main__':
    mpc.run(main())
```

I ran it:
```
python3 modmath.py -M 3
```

I expect when I run it I would get the output
```
a_bits=[0, 1, 0, 0, 1, 0]
```

But the output is non-deterministic, with the above format but a seemingly random choice of zeros and ones.

Is this a bug or am I misunderstanding something?

**Comment by lschoe** [comment]
Thanks for your report, and sorry for this late response. 

You were running into an undocumented limitation on the field order for mpc.to_bits() to work correctly with secure finite field elements. This limitation has now been removed on the MPyC master branch, so your program should now run as expected.

The secure types for finite fields are generally not very well supported (or natively good) for doing bit-oriented calculations. The secure types for integers (and fixed-point) numbers are much better for bit-oriented stuff. 

In particular, there is currently no support for comparisons such as <, >= of secure finite field elements. This is partly so because <, >= etc. are mathematically not that compatible with finite fields (especially in case of non-binary extension fields), and also  because the implementation would be somewhat awkward and not that efficient (but certainly possible).

However, as MPyC is also used to do all kinds of threshold cryptography, it makes a lot of sense to add some more support for bit-oriented operations on secure finite field types.
