### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by ThomasTNO** [lschoe/mpyc#23]
It would be very nice to have type hints implemented in MPyC. (Both for a better understanding of the code, as well as a more robust implementation)

Are there any plans to incorporate this in future versions?

https://www.python.org/dev/peps/pep-0484/

**Comment by lschoe** [comment]
Well, type hints have been pretty low on the TODO list. So it would only be in the somewhat distant future.

Are there particular parts of MPyC that you would like to see adorned with type hints? 
Parts that are particularly confusing?

**Comment by ThomasTNO** [comment]
Nothing in particular. It mostly helps in early bug discovery and discovering wrong use (in implementations dependent on MPyC) at an early stage using automated checkers (e.g., MyPy).

I must admit that fully type hinting MPyC will be quite a task.

**Comment by lschoe** [comment]
Yeah, I see you're actually using type hints a lot in [TNO-MPC](https://github.com/TNO-MPC)!

MPyC currently uses type hints in a simple way for one purpose, namely to provide an alternative to the `await returnType()` required as the first await expression in an MPyC coroutine. There is an example use of this in demos/id3gini.py:
```
@mpc.coroutine
async def id3(T, R) -> asyncio.Future:
````
And some similar usages in mpyc/runtime.py. The decorator `mpc.coroutine()` extracts the return type from the type hint for the return value, hence this will work if the type is independent of the types and dimensions of the inputs.

**Comment by ThomasTNO** [comment]
We have been working on adding type hints to (some) parts of the MPyC code. In order to be able to properly type hint the code, we needed to modify the `asyncoro` module. These modification are found here: https://github.com/TNO-MPC/mpyc.matrix_inverse/blob/main/tno/mpc/mpyc/matrix_inverse/asyncoro.py

Furthermore, the type hints stub that we created is found here: https://github.com/TNO-MPC/mpyc.stubs/tree/main/tno/mpc/mpyc/stubs

It would be great to see these (or similar) changes incorporated in MPyC.

Lastly, apart from the above mentioned packages, we also open-sourced our Kaplan-Meier solution, which leverages MPyC: https://github.com/TNO-MPC/protocols.kaplan_meier

**Comment by lschoe** [comment]
Hi Thomas, nice to see all these results! The annotated version of `mpyc/mpyc/asyncoro.py` gives a different perspective on the code. This can indeed help to catch some errors. But for the mainstream development I find it a bit heavy. Did you find any parts of the core MPyC code that need amendments?

The Kaplan-Meier package is also interesting, to see TNO's perspective on privacy-preserving survival analysis. Do you have particular performance gains compared to `mpyc/demos/kmsurvival.py` by exploiting that Alice and Bob have their own datasets in the clear?

**Comment by b-kamphorst** [comment]
Hi @lschoe, we didn't do a full comparison with `mpyc/demos/kmsurvival`. I am not entirely sure how to fairly compare them since we assume vertically-partitioned data whereas the demo assumes horizontally-partitioned data. However, I hope to find some resources to present our results in an article so if you have any thoughts on how to compare them in a meaningful way then feel free to share them!

We leverage the data partitioning heavily in the first part of our protocol which uses the Paillier cryptosystem ([TNO-MPC implementation](https://github.com/TNO-MPC/encryption_schemes.paillier)) to perform all required operations short of some multiplications and the matrix inversion for the logrank test in a single round of communication. Those final operations are performed with `mpyc`.

**Comment by marcusmjh** [comment]
Hi @lschoe , I would like to share a bit of the reasoning behind our alterations and type hinting. I worked on the type hints and noticed that the behaviour of e.g., mpyc coroutines was not very clear from first glance. A few questions that immediately arose while trying to type hint were:
1. What happens when you decorate an async function with the mpyc coroutine decorator? Why do they not return coroutines?
2. Why do we need to await `returnType` in these decorated functions?

After digging through the code, I started to understand the whole structure (The mpyc coroutine decorator specifically looks for a call to `returnType`, which passes a type to the mpyc coroutine through a generator construction to create a dummy value of that type and schedules a task that runs the coroutine and updates the dummy value when finished). This means that the MPyC coroutine translates a function that would normally return a coroutine to a function that returns an object of the type the coroutine will return when finished.

Type hints are a very nice tool to reflect this behaviour. If configured properly, an IDE can now detect that running an MPyC-decorated async function returns an object of the type that will eventually be returned by the async function. This makes debugging a lot easier and using the code more intuitive. However, in order to get the type hints to work properly, we had to change some parts of the `asyncoro.py` code. Namely,
1. `returnType` has different behaviour for different types of input for the parameter indicating the return type and for each of those, the behaviour is in turn dependent on the `wrap` parameter. In order to properly convey its behaviour in type hints, 
a) We had to split up `returnType` into `returnType` and `returnType_no_wrap`, where `returnType` simply calls `returnType_no_wrap` and wraps it up. 
b) We specified the function arguments as `return_type` for the return type and `*dimensions` for the variable number of dimensions.
c) We had to overload both functions for the different input-type-output-type relations (which means that the functions are defined multiple times with different type hints). In principle, this could also be done in a stub, but then a reader who goes to the source code to understand its behaviour will not see the type hints.
2. `mpc_coro` uses type hints in a specific way, as you mentioned earlier, but this breaks the code when we try to apply the type hinting 'properly'. We added an `ignore` parameter (boolean) to `mpc_coro` that switches off this behaviour when set to `True` and added a decorator `mpc_coro_ignore` that calls `mpc_coro` with `ignore=True`. 

We took this approach, because we wanted our alterations to be backwards-compatible. We believe that applying these changes to the `asyncoro.py` file to accommodate the type hints will benefit the whole MPyC community in the long-term. Additionally, we took the liberty to rename a couple of parameters in the functions that we rewrote for readability, but these do not need to be incorporated.

**Comment by lschoe** [comment]
Hi @b-kamphorst, yeah right, these results are not that easy to compare because the approaches are quite different. There is a rough distinction with regard to horizontal vs vertical data partitioning, but we do quite different things based on these partitions. Like you are saying, you are exploiting the private knowledge of the vertical fragments by I think two parties to gain performance. But that also ties your solution to a 3-party setting (incl. a helper party). While we are not really using the fact that parties know their horizontal fragment; it is more to show how data can be input at all, in a somewhat special way.

Once the data has been 'uploaded', and is inside the program in secret-shared form, the entire computation proceeds without using how the data came about. So, the data might as well have been input in a vertical fashion: assuming patients are assigned a unique identifier (for one-time use) that all vertical inputters have access to. The identifiers might even be publicly known as the data elements connected to these identifiers are only available in secret-shared form.

So, our computation is very general, for an arbitrary number of parties. However, to potentially speed-up the computation and to have a rough look at the Kaplan-Meier curves, to see if these kind of make sense, we have built in the option to reveal an "aggregated" Kaplan-Meier curve. For example, if the timeline is in days, and last one year, we might reveal the monthly totals. That allows us both to speed up the computation, and to show the Kaplan-Meier curve over months instead of days.

You also mentioned the use of a matrix inverse, but I was wondering how that comes into play?

**Comment by lschoe** [comment]
Hi @marcusmjh, really nice that you have taken such a close look at the MPyC coroutines. Indeed, there is quite a bit going on, but the goal is that these details need not concern the programmer that much. 

As you point out correctly, the `mpc.coroutine()` decorator technically converts a Python coroutine (defined by `async def`) into an "ordinary" function. If you call an MPyC coroutine you don't have to await it, and magically, it doesn't block either. It returns immediately and gives you a placeholder, like a `asyncio.Future`, which will receive a result at some point later on. The placeholders are typed, and in fact there can be lots of placeholders packed together--currently nested lists are supported to keep the implementation simple.

Under the hood the call to an MPyC coroutine will indeed create a task (an `asyncio.Task`), and for that reason I've considered the name `mpc.task()` instead of `mpc.coroutine()`, to emphasize that aspect. However, this implementation detail of using an `asyncio.Task` and more broadly, the use of an event loop with all its intricacies should be hidden as much as possible. For most programmers it should be OK to be unaware of the event loop and tasks (that's also the goal with `asyncio`, where current versions of Python are hiding the (running) event loop as much as possible).

And, in fact an MPyC coroutine is still executed as a coroutine, yielding to the event loop at `await` expressions. 

The way the first `await` is handled in an MPyc coroutine is special, because there the specification of the return type containing the empty placeholders should be given. That seems to be the most reasonable way to do this. I mean reasonable, in the sense of not interfering with the inner-workings of a Python function, setting things up that there should be a line in the function body of a special format, say `returnType()`. So almost the same as `await returnType()` , but the decorator would then parse the function body, and extract that special line. 

The rule of "the first `await` is special" is less intrusive and the option of choice for now. The extra option to use the `return` type annotation is interesting too, because the special `await` is then avoided. However---as you undoubtedly know---the annotation is processed "statically" when the function is loaded by the Python interpreter. That means, that the `returnType` thus defined cannot depend on the input to the MPyC coroutine. So, we cannot return a list where the length of the list varies with each call.
We actually want to tell each caller how long the output is, so that the program can continue to create tasks as many as needed.

A way out is to make that annotation contain an expression, which will only be evaluated (using Python's built-in `eval()`) . As it is currently, with static types, I think it can be combined with the type checking that you do. That there is no real conflict. Because the type used for type checking can tell 'returnType()' what to, hence what kind of placeholders to create. Do you see a problem there?

**Comment by b-kamphorst** [comment]
> Hi @b-kamphorst, yeah right, these results are not that easy to compare because the approaches are quite different. There is a rough distinction with regard to horizontal vs vertical data partitioning, but we do quite different things based on these partitions. Like you are saying, you are exploiting the private knowledge of the vertical fragments by I think two parties to gain performance. But that also ties your solution to a 3-party setting (incl. a helper party). While we are not really using the fact that parties know their horizontal fragment; it is more to show how data can be input at all, in a somewhat special way.

Indeed, the current solution requires a third party only to work with MPyC. These components could be replaced by 2-player frameworks, but for now there was no need to do so + we like working with MPyC.

> Once the data has been 'uploaded', and is inside the program in secret-shared form, the entire computation proceeds without using how the data came about. So, the data might as well have been input in a vertical fashion: assuming patients are assigned a unique identifier (for one-time use) that all vertical inputters have access to. The identifiers might even be publicly known as the data elements connected to these identifiers are only available in secret-shared form.

Using the MPyC implementation on vertically-partitioned data is not quite as straightforward as you seem to suggest. Most notably, looking at your nice [KM notebook](https://github.com/lschoe/mpyc/blob/master/demos/KaplanMeierSurvivalExplained.ipynb), it seems that you require separate `(ni, di)`-formatted datasets per patient group `i`. In our setting, one of the parties knows the event time and status of every patient and another party knows the patient group. In particular, there needs to be some pre-phase to your solution that enables the parties to make that distinction -- and of course we'd like that phase to be efficient as well (e.g. no secure comparisons).

> So, our computation is very general, for an arbitrary number of parties. However, to potentially speed-up the computation and to have a rough look at the Kaplan-Meier curves, to see if these kind of make sense, we have built in the option to reveal an "aggregated" Kaplan-Meier curve. For example, if the timeline is in days, and last one year, we might reveal the monthly totals. That allows us both to speed up the computation, and to show the Kaplan-Meier curve over months instead of days.

We indeed did not implement (or leverage your) functionality to reveal aggregated Kaplan-Meier curves since this was of lower priority to our customer. They once mentioned that biomedical papers might not accept non-exact curves. I would like to see that hypothesis tested -- do you intend to do so in the near future?

> You also mentioned the use of a matrix inverse, but I was wondering how that comes into play?

Our implementation supports more than two patient groups, so that the division in the 2-group logrank test ([`vtot`](https://github.com/lschoe/mpyc/blob/c217dd477acc9ca2a988b16af729473962178767/demos/kmsurvival.py#L134)) turns into a multiplication by a inversed matrix (cf. page 12 of [these lecture notes](https://web.stanford.edu/~lutian/coursepdf/unitweek3.pdf)).

**Comment by lschoe** [comment]
Thanks @b-kamphorst, this helps a lot. Interesting to learn about the generalization to more than two groups, with the matrix inverse popping up naturally. 

I'm not working on this topic really. Meilof Veeningen and others worked on this at Philips a few years ago now. I don't think we ever discussed if biomedical journals would oppose against such non-exact curves. But they might accept the idea if they see the privacy benefit. And it's also very important to get the point across that even though the curves are not exact, the curves are still based on the actual data. It's not like the authors of the paper fabricating or manipulating the data. 

And I see your point with the vertically-partitioned data. It looks like it's still easy to join the two datasets by requiring that both parties sort their data records based on a common identifier (pseudonym) used for each patient. They then secret-share their respective parts of the data records of all patients to form a secret-shared table containing all data. 

But the problem of efficiently turning this secret-shared table into a secret-shared survival table indeed looks challenging. And interesting too because the two parties can reveal some rough information to limit the work a bit, and use their private knowledge. I'll have a closer look at your solution when I find some time for it.
