### ISSUE TITLE
Using lpsolver.py

### ISSUE THREAD

**Issue by MurtAlsa** [lschoe/mpyc#31]
Thank you for your excellent work!

I have been using your library for a while. I am now trying to use the "lpsolver.py" for a particular dataset. However, I am unsure how to set the correct "bit-length." Can you elaborate more, please? 

Best,

**Comment by lschoe** [comment]
Oh, thanks!

Indeed to find the right bit length may be a bit tricky, especially if the dataset is large and you cannot try out options quickly (although a binary search should kind of work). But maybe first an important sanity check: namely if your dataset has x=0 as a feasible solution, which means that b >=0 is assumed to hold.

If  b>=0 and hence x=0 is feasible, then there are in principle "Hadamard style" bounds for the lengths of the integers that will arise during the computation, as a function of the bit length of the numbers in the dataset and of the number of variables and the number of constraints. Not sure if you want to look into this. 

(One further thing maybe, if your datasets contains floats you need to scale these to integers.)

**Comment by lschoe** [comment]
Hi, you can indeed adapt the code to handle a minimization problem instead of a maximization problem.

Here are the minimal changes that you need to apply:

1. Replace function `argmin_int()` by its counterpart `argmax_int()`.
2. Negate the top row of the tableau `T` right after its initialization by inserting `T[0] = [-a for a in T[0]]`.
3. In the main loop of the Simplex algorithm, now call `argmax_int()` like this: `p_col_index, maximum = argmax_int(T[0][:-1])`.
4. And change the corresponding termination condition into:  `await mpc.output(maximum <= 0)`.

I think this solves the corresponding minimization problem. (The print statements and the verification also need to be adapted if you want those to be correct as well).

**Comment by MurtAlsa** [comment]
That's correct. I am trying to adopt the code to work on a dynamic constrains forms that any kind of inequalities LP problem (  Something like what's proposed in the CPLEX) Please provide any sugession.

**Comment by lschoe** [comment]
If x=0 is not known to be a feasible solution, you need to find a feasible solution using another run of the secure Simplex algorithm on a suitably defined LP problem instance. Sebastiaan de Hoogh worked out the details for secure initializations using several methods. See Section 3.3 "Implementations of the Simplex Initializations" of his PhD thesis [Design of Large Scale Applications of Secure Multiparty Computation: Secure Linear Programming](https://doi.org/10.6100/IR735328).

**Comment by MurtAlsa** [comment]
Hello @lschoe

Is there any way that I can set zero as starting initialized point. Since zero is a visible solution as per your explanation earlier. And I would like to take an advantage of that.

**Comment by lschoe** [comment]
The MPyC demo lpsolver.py includes pointers to the papers on which it is based. To extend the program for the case that x=0 is not a feasible solution is covered in Sebastiaan de Hoogh's PhD thesis mentioned above. However, this material is quite advanced if you're not familiar with the Simplex algorithm and its variants.
