### ISSUE TITLE
Questions about the implementation of secure ID3

### ISSUE THREAD

**Issue by DylanWangWQF** [lschoe/mpyc#38]
Hi, @lschoe  
I try to run`mpyc` for some benchmark results on secure ID3 decision tree training.
I checked your paper "Practical Secure Decision Tree Learning in a Teletreatment Application", there are three algorithms that provide different security levels. 

- SID3, public the result tree
- SID3T, reveals only the depth of each path.
- SID3P, horizontally partition the dataset and public the result tree.

Currently, I'm not that familiar with the protocols in the paper
In `mpyc`, it seems that you only implement `SID3`.
https://github.com/lschoe/mpyc/blob/98766105a1567a59e35fab4234a59fc0a407118c/demos/id3gini.py#L18

Do we implement `SID3T` which provides a higher security level? I want to compare it with SID3T.

**Comment by DylanWangWQF** [comment]
Hi @lschoe 

BTW, are the original implementation in VIFF available currently?

**Comment by lschoe** [comment]
Hi @DylanWangWQF

OK, I'm attaching a copy (as a text file) of the Python 2 code [ID3-Gini2T.py.txt](https://github.com/lschoe/mpyc/files/10206543/ID3-Gini2T.py.txt) that we used at the time for the paper. It's for the SID3T protocol. You may be able to write your own version of SID3T in MPyC based in this code.

This code ran on our TUE extension of VIFF, also relying on Marcel Keller's boost extension of VIFF, to get better performance at the time. The [np_id3gini.py](https://github.com/lschoe/mpyc/blob/master/demos/np_id3gini.py) demo improved a lot since then, like for the [KRKPA7](https://github.com/lschoe/mpyc/blob/master/demos/data/id3/KRKPA7.csv) dataset it runs well below 4s on my somewhat dated [i7-4790](https://en.wikipedia.org/wiki/Haswell_(microarchitecture)) desktop, compared to 46s reported in the paper on a slightly older [i5-3470](https://en.wikipedia.org/wiki/Ivy_Bridge_(microarchitecture)).

Also note that the code actually reveals the secretly computed decision tree, but this is not essential, only to be able to print it somewhat easily.

**Comment by DylanWangWQF** [comment]
@lschoe 
Thanks a lot! This really saves me time. 
I will try to implement a version in MPyC based on this code.

**Comment by DylanWangWQF** [comment]
HI @lschoe  
Sry for my frequent questions. I'm writing the code, but I don't know what the previous functions do. (i.e., `lin_comb`)

```
ID3-Gini2T.py
(1).
T_C_s = [self.check(self.runtime.in_prod(v,T)) for v in self.V[self.C][:-1]]
T_C_s.append(s-sum(T_C_s))
max, max_sid = self.int_max(T_C_s)
max_id = self.runtime.lin_comb([i for i in xrange(len(max_sid))],max_sid)

(2).
gains = [self.GIT(self.check(self.runtime.matrix_prod(self.V[RR[a]], T_C)), R[a]) for a in xrange(len(R))]
ii = self.frac_max(gains)
i = self.runtime.open(self.runtime.lin_comb(RR,ii))	
A = int(i.value)

ell = len(self.V[0])
self.active_nodes += ell - 1
R_A = map(operator.add, R, ii) 
V_A = [[self.runtime.in_prod([self.V[k][j][l] for k in RR], ii) for l in xrange(len(self.V[0][0]))] for j in xrange(ell)]
```

```
id3gini.py
(1).
sizes = [mpc.in_prod(T, v) for v in S[C]]
i, mx = mpc.argmax(sizes)

(2).
gains = [GI(mpc.matrix_prod(S[A], T_SC, True)) for A in R]
k = await mpc.output(mpc.argmax(gains, key=SecureFraction)[0])
A = list(R)[k]
```

1. `lin_comb` appears to be a mapping, what are the coefficients of this combination?
2. When we use the `r` to indicate the stopping criteria (i.e., attributes/depth), the param `active_nodes` in `ID3-Gini2T.py`  is still necessary?

**Comment by DylanWangWQF** [comment]
Here is a draft version of [SID3T.py.txt](https://github.com/lschoe/mpyc/files/10225126/SID3T.py.txt) (test with **binary** features, [binary_tennis.csv](https://github.com/lschoe/mpyc/files/10225132/binary_tennis.csv)), the error occurs in `in_prod([self.V[k][j][l] for k in RR], ii);`

I'm now investigating the difference between old `frac_max` and existing `argmax ` (I used other libraries before and am not that familiar with mpyc).
