### ISSUE TITLE
Limit on number of localhost parties

### ISSUE THREAD

**Issue by AlexConnat** [lschoe/mpyc#4]
I realised running localhost computations using `-M` >= 20 number of parties is extremely slow (From 2 to 15, I measured the time it took, and it reasonably quadratically grows, but after 20, it explodes. Do you know whether this is a limitation of the library, or rather a problem on my side (hardware specs, etc...?)

**Comment by lschoe** [comment]
Yes, that should be pretty slow;) In general, MPC with so many parties is hard to do efficiently. Many MPC frameworks are therefore limited to a handful of parties, often just two or three.

MPyC has a built-in limit at m=256 parties. But that limit cannot be reached using the maximum threshold of t=(m-1)//2, because MPyC relies on pseudorandom secret sharing (PRSS). The running time is therefore proportional to (m choose t)=m!/(m-t)!/t!, which is even exponential in m at maximum threshold t.

By using a small threshold t, you'll get things going again. For example, you can run the OT demo (mpyc/demos/ot.py) with m=101 and threshold t=1 like this   

`python ot.py -M101 -T1`

Don't expect lightning speed, as the parties will use m(m-1)/2=5050 TCP connections between them on localhost. 

What kind of MPC would you like to run with so many parties?

**Comment by abdelrahamanaly** [comment]
HI Berry,
Silly question,  where does the factorial terms on the running times that
you give come from? It is not clear to me the relation with PRSS and that
performance explosion.
Thanks so much in advance

**Comment by lschoe** [comment]
Hi,

 

Maybe it’s easiest to take a look at the code. There’s the function threshold() in mpyc.runtime, lines 66-78:

 

    @threshold.setter

    def threshold(self, t):

        self._threshold = t

        # generate new PRSS keys

        self.prfs.cache_clear()

        keys = {}

        m = len(self.parties)

        for subset in itertools.combinations(range(m), m - t):

            if self.pid == min(subset):

                keys[subset] = secrets.token_bytes(16)  # 128-bit key

        self._prss_keys = keys

        # caching (m choose t):

        self._bincoef = math.factorial(m) // math.factorial(t) // math.factorial(m - t)

 

Here you see a loop with (m choose m-t) = (m choose t) iterations. Also, when mpc.start() is executed similar things are done. E.g., in mpyc.asyncoro, there is this code:

 

    def connection_made(self, transport):

        """Called when a connection is made.

 

        If the party is a client for this connection, it sends its identity

        to the peer as well as any PRSS keys.

        """

        self.transport = transport

        if self.peer_pid is not None:  # party is client (peer is server)

            m = len(self.runtime.parties)

            t = self.runtime.threshold

            pid_keys = self.runtime.pid.to_bytes(1, 'little')  # send pid

            for subset in itertools.combinations(range(m), m - t):

                if self.peer_pid in subset and self.runtime.pid == min(subset):

                    pid_keys += self.runtime._prss_keys[subset]  # send PRSS keys

            transport.write(pid_keys)

            self._key_transport_done()

 

And similar code in the data_received() method. 

 

That shows the typical exponential effect for PRSS. 

 

Hope this helps you a bit,

  Berry

**Comment by abdelrahamanaly** [comment]
Thanks Berry, indeed that is more clear now. Thanks for the kind an
complete answer
